// Code generated by entc, DO NOT EDIT.

package registrationinvitation

const (
	// Label holds the string label denoting the registrationinvitation type in the database.
	Label = "registration_invitation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the registrationinvitation in the database.
	Table = "registration_invitations"
)

// Columns holds all SQL columns for registrationinvitation fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
