// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/appcouponsetting"
)

// AppCouponSettingCreate is the builder for creating a AppCouponSetting entity.
type AppCouponSettingCreate struct {
	config
	mutation *AppCouponSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// Mutation returns the AppCouponSettingMutation object of the builder.
func (acsc *AppCouponSettingCreate) Mutation() *AppCouponSettingMutation {
	return acsc.mutation
}

// Save creates the AppCouponSetting in the database.
func (acsc *AppCouponSettingCreate) Save(ctx context.Context) (*AppCouponSetting, error) {
	var (
		err  error
		node *AppCouponSetting
	)
	if len(acsc.hooks) == 0 {
		if err = acsc.check(); err != nil {
			return nil, err
		}
		node, err = acsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppCouponSettingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = acsc.check(); err != nil {
				return nil, err
			}
			acsc.mutation = mutation
			if node, err = acsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(acsc.hooks) - 1; i >= 0; i-- {
			if acsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = acsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, acsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (acsc *AppCouponSettingCreate) SaveX(ctx context.Context) *AppCouponSetting {
	v, err := acsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acsc *AppCouponSettingCreate) Exec(ctx context.Context) error {
	_, err := acsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acsc *AppCouponSettingCreate) ExecX(ctx context.Context) {
	if err := acsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acsc *AppCouponSettingCreate) check() error {
	return nil
}

func (acsc *AppCouponSettingCreate) sqlSave(ctx context.Context) (*AppCouponSetting, error) {
	_node, _spec := acsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, acsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (acsc *AppCouponSettingCreate) createSpec() (*AppCouponSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &AppCouponSetting{config: acsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: appcouponsetting.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: appcouponsetting.FieldID,
			},
		}
	)
	_spec.OnConflict = acsc.conflict
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppCouponSetting.Create().
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (acsc *AppCouponSettingCreate) OnConflict(opts ...sql.ConflictOption) *AppCouponSettingUpsertOne {
	acsc.conflict = opts
	return &AppCouponSettingUpsertOne{
		create: acsc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppCouponSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (acsc *AppCouponSettingCreate) OnConflictColumns(columns ...string) *AppCouponSettingUpsertOne {
	acsc.conflict = append(acsc.conflict, sql.ConflictColumns(columns...))
	return &AppCouponSettingUpsertOne{
		create: acsc,
	}
}

type (
	// AppCouponSettingUpsertOne is the builder for "upsert"-ing
	//  one AppCouponSetting node.
	AppCouponSettingUpsertOne struct {
		create *AppCouponSettingCreate
	}

	// AppCouponSettingUpsert is the "OnConflict" setter.
	AppCouponSettingUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AppCouponSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AppCouponSettingUpsertOne) UpdateNewValues() *AppCouponSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.AppCouponSetting.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *AppCouponSettingUpsertOne) Ignore() *AppCouponSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppCouponSettingUpsertOne) DoNothing() *AppCouponSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppCouponSettingCreate.OnConflict
// documentation for more info.
func (u *AppCouponSettingUpsertOne) Update(set func(*AppCouponSettingUpsert)) *AppCouponSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppCouponSettingUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AppCouponSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppCouponSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppCouponSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppCouponSettingUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppCouponSettingUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppCouponSettingCreateBulk is the builder for creating many AppCouponSetting entities in bulk.
type AppCouponSettingCreateBulk struct {
	config
	builders []*AppCouponSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the AppCouponSetting entities in the database.
func (acscb *AppCouponSettingCreateBulk) Save(ctx context.Context) ([]*AppCouponSetting, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acscb.builders))
	nodes := make([]*AppCouponSetting, len(acscb.builders))
	mutators := make([]Mutator, len(acscb.builders))
	for i := range acscb.builders {
		func(i int, root context.Context) {
			builder := acscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppCouponSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acscb *AppCouponSettingCreateBulk) SaveX(ctx context.Context) []*AppCouponSetting {
	v, err := acscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acscb *AppCouponSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := acscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acscb *AppCouponSettingCreateBulk) ExecX(ctx context.Context) {
	if err := acscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppCouponSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (acscb *AppCouponSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppCouponSettingUpsertBulk {
	acscb.conflict = opts
	return &AppCouponSettingUpsertBulk{
		create: acscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppCouponSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (acscb *AppCouponSettingCreateBulk) OnConflictColumns(columns ...string) *AppCouponSettingUpsertBulk {
	acscb.conflict = append(acscb.conflict, sql.ConflictColumns(columns...))
	return &AppCouponSettingUpsertBulk{
		create: acscb,
	}
}

// AppCouponSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of AppCouponSetting nodes.
type AppCouponSettingUpsertBulk struct {
	create *AppCouponSettingCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppCouponSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AppCouponSettingUpsertBulk) UpdateNewValues() *AppCouponSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppCouponSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *AppCouponSettingUpsertBulk) Ignore() *AppCouponSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppCouponSettingUpsertBulk) DoNothing() *AppCouponSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppCouponSettingCreateBulk.OnConflict
// documentation for more info.
func (u *AppCouponSettingUpsertBulk) Update(set func(*AppCouponSettingUpsert)) *AppCouponSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppCouponSettingUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AppCouponSettingUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppCouponSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppCouponSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppCouponSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
