// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/appinvitationsetting"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppInvitationSettingQuery is the builder for querying AppInvitationSetting entities.
type AppInvitationSettingQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppInvitationSetting
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppInvitationSettingQuery builder.
func (aisq *AppInvitationSettingQuery) Where(ps ...predicate.AppInvitationSetting) *AppInvitationSettingQuery {
	aisq.predicates = append(aisq.predicates, ps...)
	return aisq
}

// Limit adds a limit step to the query.
func (aisq *AppInvitationSettingQuery) Limit(limit int) *AppInvitationSettingQuery {
	aisq.limit = &limit
	return aisq
}

// Offset adds an offset step to the query.
func (aisq *AppInvitationSettingQuery) Offset(offset int) *AppInvitationSettingQuery {
	aisq.offset = &offset
	return aisq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aisq *AppInvitationSettingQuery) Unique(unique bool) *AppInvitationSettingQuery {
	aisq.unique = &unique
	return aisq
}

// Order adds an order step to the query.
func (aisq *AppInvitationSettingQuery) Order(o ...OrderFunc) *AppInvitationSettingQuery {
	aisq.order = append(aisq.order, o...)
	return aisq
}

// First returns the first AppInvitationSetting entity from the query.
// Returns a *NotFoundError when no AppInvitationSetting was found.
func (aisq *AppInvitationSettingQuery) First(ctx context.Context) (*AppInvitationSetting, error) {
	nodes, err := aisq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appinvitationsetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) FirstX(ctx context.Context) *AppInvitationSetting {
	node, err := aisq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppInvitationSetting ID from the query.
// Returns a *NotFoundError when no AppInvitationSetting ID was found.
func (aisq *AppInvitationSettingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aisq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appinvitationsetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aisq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppInvitationSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppInvitationSetting entity is found.
// Returns a *NotFoundError when no AppInvitationSetting entities are found.
func (aisq *AppInvitationSettingQuery) Only(ctx context.Context) (*AppInvitationSetting, error) {
	nodes, err := aisq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appinvitationsetting.Label}
	default:
		return nil, &NotSingularError{appinvitationsetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) OnlyX(ctx context.Context) *AppInvitationSetting {
	node, err := aisq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppInvitationSetting ID in the query.
// Returns a *NotSingularError when more than one AppInvitationSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (aisq *AppInvitationSettingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aisq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appinvitationsetting.Label}
	default:
		err = &NotSingularError{appinvitationsetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aisq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppInvitationSettings.
func (aisq *AppInvitationSettingQuery) All(ctx context.Context) ([]*AppInvitationSetting, error) {
	if err := aisq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aisq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) AllX(ctx context.Context) []*AppInvitationSetting {
	nodes, err := aisq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppInvitationSetting IDs.
func (aisq *AppInvitationSettingQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := aisq.Select(appinvitationsetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aisq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aisq *AppInvitationSettingQuery) Count(ctx context.Context) (int, error) {
	if err := aisq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aisq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) CountX(ctx context.Context) int {
	count, err := aisq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aisq *AppInvitationSettingQuery) Exist(ctx context.Context) (bool, error) {
	if err := aisq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aisq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aisq *AppInvitationSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := aisq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppInvitationSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aisq *AppInvitationSettingQuery) Clone() *AppInvitationSettingQuery {
	if aisq == nil {
		return nil
	}
	return &AppInvitationSettingQuery{
		config:     aisq.config,
		limit:      aisq.limit,
		offset:     aisq.offset,
		order:      append([]OrderFunc{}, aisq.order...),
		predicates: append([]predicate.AppInvitationSetting{}, aisq.predicates...),
		// clone intermediate query.
		sql:    aisq.sql.Clone(),
		path:   aisq.path,
		unique: aisq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppInvitationSetting.Query().
//		GroupBy(appinvitationsetting.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aisq *AppInvitationSettingQuery) GroupBy(field string, fields ...string) *AppInvitationSettingGroupBy {
	grbuild := &AppInvitationSettingGroupBy{config: aisq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aisq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aisq.sqlQuery(ctx), nil
	}
	grbuild.label = appinvitationsetting.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppInvitationSetting.Query().
//		Select(appinvitationsetting.FieldAppID).
//		Scan(ctx, &v)
//
func (aisq *AppInvitationSettingQuery) Select(fields ...string) *AppInvitationSettingSelect {
	aisq.fields = append(aisq.fields, fields...)
	selbuild := &AppInvitationSettingSelect{AppInvitationSettingQuery: aisq}
	selbuild.label = appinvitationsetting.Label
	selbuild.flds, selbuild.scan = &aisq.fields, selbuild.Scan
	return selbuild
}

func (aisq *AppInvitationSettingQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aisq.fields {
		if !appinvitationsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aisq.path != nil {
		prev, err := aisq.path(ctx)
		if err != nil {
			return err
		}
		aisq.sql = prev
	}
	return nil
}

func (aisq *AppInvitationSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppInvitationSetting, error) {
	var (
		nodes = []*AppInvitationSetting{}
		_spec = aisq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*AppInvitationSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &AppInvitationSetting{config: aisq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(aisq.modifiers) > 0 {
		_spec.Modifiers = aisq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aisq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aisq *AppInvitationSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aisq.querySpec()
	if len(aisq.modifiers) > 0 {
		_spec.Modifiers = aisq.modifiers
	}
	_spec.Node.Columns = aisq.fields
	if len(aisq.fields) > 0 {
		_spec.Unique = aisq.unique != nil && *aisq.unique
	}
	return sqlgraph.CountNodes(ctx, aisq.driver, _spec)
}

func (aisq *AppInvitationSettingQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aisq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aisq *AppInvitationSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appinvitationsetting.Table,
			Columns: appinvitationsetting.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appinvitationsetting.FieldID,
			},
		},
		From:   aisq.sql,
		Unique: true,
	}
	if unique := aisq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aisq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appinvitationsetting.FieldID)
		for i := range fields {
			if fields[i] != appinvitationsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aisq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aisq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aisq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aisq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aisq *AppInvitationSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aisq.driver.Dialect())
	t1 := builder.Table(appinvitationsetting.Table)
	columns := aisq.fields
	if len(columns) == 0 {
		columns = appinvitationsetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aisq.sql != nil {
		selector = aisq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aisq.unique != nil && *aisq.unique {
		selector.Distinct()
	}
	for _, m := range aisq.modifiers {
		m(selector)
	}
	for _, p := range aisq.predicates {
		p(selector)
	}
	for _, p := range aisq.order {
		p(selector)
	}
	if offset := aisq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aisq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aisq *AppInvitationSettingQuery) Modify(modifiers ...func(s *sql.Selector)) *AppInvitationSettingSelect {
	aisq.modifiers = append(aisq.modifiers, modifiers...)
	return aisq.Select()
}

// AppInvitationSettingGroupBy is the group-by builder for AppInvitationSetting entities.
type AppInvitationSettingGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aisgb *AppInvitationSettingGroupBy) Aggregate(fns ...AggregateFunc) *AppInvitationSettingGroupBy {
	aisgb.fns = append(aisgb.fns, fns...)
	return aisgb
}

// Scan applies the group-by query and scans the result into the given value.
func (aisgb *AppInvitationSettingGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aisgb.path(ctx)
	if err != nil {
		return err
	}
	aisgb.sql = query
	return aisgb.sqlScan(ctx, v)
}

func (aisgb *AppInvitationSettingGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aisgb.fields {
		if !appinvitationsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aisgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aisgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aisgb *AppInvitationSettingGroupBy) sqlQuery() *sql.Selector {
	selector := aisgb.sql.Select()
	aggregation := make([]string, 0, len(aisgb.fns))
	for _, fn := range aisgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(aisgb.fields)+len(aisgb.fns))
		for _, f := range aisgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(aisgb.fields...)...)
}

// AppInvitationSettingSelect is the builder for selecting fields of AppInvitationSetting entities.
type AppInvitationSettingSelect struct {
	*AppInvitationSettingQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aiss *AppInvitationSettingSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aiss.prepareQuery(ctx); err != nil {
		return err
	}
	aiss.sql = aiss.AppInvitationSettingQuery.sqlQuery(ctx)
	return aiss.sqlScan(ctx, v)
}

func (aiss *AppInvitationSettingSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aiss.sql.Query()
	if err := aiss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aiss *AppInvitationSettingSelect) Modify(modifiers ...func(s *sql.Selector)) *AppInvitationSettingSelect {
	aiss.modifiers = append(aiss.modifiers, modifiers...)
	return aiss
}
