// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/commissioncoinsetting"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/predicate"
)

// CommissionCoinSettingDelete is the builder for deleting a CommissionCoinSetting entity.
type CommissionCoinSettingDelete struct {
	config
	hooks    []Hook
	mutation *CommissionCoinSettingMutation
}

// Where appends a list predicates to the CommissionCoinSettingDelete builder.
func (ccsd *CommissionCoinSettingDelete) Where(ps ...predicate.CommissionCoinSetting) *CommissionCoinSettingDelete {
	ccsd.mutation.Where(ps...)
	return ccsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ccsd *CommissionCoinSettingDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ccsd.hooks) == 0 {
		affected, err = ccsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommissionCoinSettingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ccsd.mutation = mutation
			affected, err = ccsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ccsd.hooks) - 1; i >= 0; i-- {
			if ccsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ccsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ccsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccsd *CommissionCoinSettingDelete) ExecX(ctx context.Context) int {
	n, err := ccsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ccsd *CommissionCoinSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: commissioncoinsetting.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: commissioncoinsetting.FieldID,
			},
		},
	}
	if ps := ccsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ccsd.driver, _spec)
}

// CommissionCoinSettingDeleteOne is the builder for deleting a single CommissionCoinSetting entity.
type CommissionCoinSettingDeleteOne struct {
	ccsd *CommissionCoinSettingDelete
}

// Exec executes the deletion query.
func (ccsdo *CommissionCoinSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := ccsdo.ccsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{commissioncoinsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ccsdo *CommissionCoinSettingDeleteOne) ExecX(ctx context.Context) {
	ccsdo.ccsd.ExecX(ctx)
}
