// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/discountpool"
	"github.com/google/uuid"
)

// DiscountPool is the model entity for the DiscountPool schema.
type DiscountPool struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// Value holds the value of the "value" field.
	Value uint64 `json:"value,omitempty"`
	// ReleaseByUserID holds the value of the "release_by_user_id" field.
	ReleaseByUserID uuid.UUID `json:"release_by_user_id,omitempty"`
	// Start holds the value of the "start" field.
	Start uint32 `json:"start,omitempty"`
	// DurationDays holds the value of the "duration_days" field.
	DurationDays int32 `json:"duration_days,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt uint32 `json:"create_at,omitempty"`
	// UpdateAt holds the value of the "update_at" field.
	UpdateAt uint32 `json:"update_at,omitempty"`
	// DeleteAt holds the value of the "delete_at" field.
	DeleteAt uint32 `json:"delete_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscountPool) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case discountpool.FieldValue, discountpool.FieldStart, discountpool.FieldDurationDays, discountpool.FieldCreateAt, discountpool.FieldUpdateAt, discountpool.FieldDeleteAt:
			values[i] = new(sql.NullInt64)
		case discountpool.FieldMessage, discountpool.FieldName:
			values[i] = new(sql.NullString)
		case discountpool.FieldID, discountpool.FieldAppID, discountpool.FieldReleaseByUserID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type DiscountPool", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscountPool fields.
func (dp *DiscountPool) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discountpool.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dp.ID = *value
			}
		case discountpool.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				dp.AppID = *value
			}
		case discountpool.FieldValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				dp.Value = uint64(value.Int64)
			}
		case discountpool.FieldReleaseByUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field release_by_user_id", values[i])
			} else if value != nil {
				dp.ReleaseByUserID = *value
			}
		case discountpool.FieldStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start", values[i])
			} else if value.Valid {
				dp.Start = uint32(value.Int64)
			}
		case discountpool.FieldDurationDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_days", values[i])
			} else if value.Valid {
				dp.DurationDays = int32(value.Int64)
			}
		case discountpool.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				dp.Message = value.String
			}
		case discountpool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				dp.Name = value.String
			}
		case discountpool.FieldCreateAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				dp.CreateAt = uint32(value.Int64)
			}
		case discountpool.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				dp.UpdateAt = uint32(value.Int64)
			}
		case discountpool.FieldDeleteAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete_at", values[i])
			} else if value.Valid {
				dp.DeleteAt = uint32(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this DiscountPool.
// Note that you need to call DiscountPool.Unwrap() before calling this method if this DiscountPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (dp *DiscountPool) Update() *DiscountPoolUpdateOne {
	return (&DiscountPoolClient{config: dp.config}).UpdateOne(dp)
}

// Unwrap unwraps the DiscountPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dp *DiscountPool) Unwrap() *DiscountPool {
	tx, ok := dp.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscountPool is not a transactional entity")
	}
	dp.config.driver = tx.drv
	return dp
}

// String implements the fmt.Stringer.
func (dp *DiscountPool) String() string {
	var builder strings.Builder
	builder.WriteString("DiscountPool(")
	builder.WriteString(fmt.Sprintf("id=%v", dp.ID))
	builder.WriteString(", app_id=")
	builder.WriteString(fmt.Sprintf("%v", dp.AppID))
	builder.WriteString(", value=")
	builder.WriteString(fmt.Sprintf("%v", dp.Value))
	builder.WriteString(", release_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", dp.ReleaseByUserID))
	builder.WriteString(", start=")
	builder.WriteString(fmt.Sprintf("%v", dp.Start))
	builder.WriteString(", duration_days=")
	builder.WriteString(fmt.Sprintf("%v", dp.DurationDays))
	builder.WriteString(", message=")
	builder.WriteString(dp.Message)
	builder.WriteString(", name=")
	builder.WriteString(dp.Name)
	builder.WriteString(", create_at=")
	builder.WriteString(fmt.Sprintf("%v", dp.CreateAt))
	builder.WriteString(", update_at=")
	builder.WriteString(fmt.Sprintf("%v", dp.UpdateAt))
	builder.WriteString(", delete_at=")
	builder.WriteString(fmt.Sprintf("%v", dp.DeleteAt))
	builder.WriteByte(')')
	return builder.String()
}

// DiscountPools is a parsable slice of DiscountPool.
type DiscountPools []*DiscountPool

func (dp DiscountPools) config(cfg config) {
	for _i := range dp {
		dp[_i].config = cfg
	}
}
