// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/userinvitationcode"
)

// UserInvitationCodeCreate is the builder for creating a UserInvitationCode entity.
type UserInvitationCodeCreate struct {
	config
	mutation *UserInvitationCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// Mutation returns the UserInvitationCodeMutation object of the builder.
func (uicc *UserInvitationCodeCreate) Mutation() *UserInvitationCodeMutation {
	return uicc.mutation
}

// Save creates the UserInvitationCode in the database.
func (uicc *UserInvitationCodeCreate) Save(ctx context.Context) (*UserInvitationCode, error) {
	var (
		err  error
		node *UserInvitationCode
	)
	if len(uicc.hooks) == 0 {
		if err = uicc.check(); err != nil {
			return nil, err
		}
		node, err = uicc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserInvitationCodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uicc.check(); err != nil {
				return nil, err
			}
			uicc.mutation = mutation
			if node, err = uicc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uicc.hooks) - 1; i >= 0; i-- {
			if uicc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uicc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uicc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uicc *UserInvitationCodeCreate) SaveX(ctx context.Context) *UserInvitationCode {
	v, err := uicc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uicc *UserInvitationCodeCreate) Exec(ctx context.Context) error {
	_, err := uicc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uicc *UserInvitationCodeCreate) ExecX(ctx context.Context) {
	if err := uicc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uicc *UserInvitationCodeCreate) check() error {
	return nil
}

func (uicc *UserInvitationCodeCreate) sqlSave(ctx context.Context) (*UserInvitationCode, error) {
	_node, _spec := uicc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uicc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (uicc *UserInvitationCodeCreate) createSpec() (*UserInvitationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &UserInvitationCode{config: uicc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userinvitationcode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userinvitationcode.FieldID,
			},
		}
	)
	_spec.OnConflict = uicc.conflict
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserInvitationCode.Create().
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (uicc *UserInvitationCodeCreate) OnConflict(opts ...sql.ConflictOption) *UserInvitationCodeUpsertOne {
	uicc.conflict = opts
	return &UserInvitationCodeUpsertOne{
		create: uicc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserInvitationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (uicc *UserInvitationCodeCreate) OnConflictColumns(columns ...string) *UserInvitationCodeUpsertOne {
	uicc.conflict = append(uicc.conflict, sql.ConflictColumns(columns...))
	return &UserInvitationCodeUpsertOne{
		create: uicc,
	}
}

type (
	// UserInvitationCodeUpsertOne is the builder for "upsert"-ing
	//  one UserInvitationCode node.
	UserInvitationCodeUpsertOne struct {
		create *UserInvitationCodeCreate
	}

	// UserInvitationCodeUpsert is the "OnConflict" setter.
	UserInvitationCodeUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserInvitationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *UserInvitationCodeUpsertOne) UpdateNewValues() *UserInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.UserInvitationCode.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *UserInvitationCodeUpsertOne) Ignore() *UserInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserInvitationCodeUpsertOne) DoNothing() *UserInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserInvitationCodeCreate.OnConflict
// documentation for more info.
func (u *UserInvitationCodeUpsertOne) Update(set func(*UserInvitationCodeUpsert)) *UserInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserInvitationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *UserInvitationCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserInvitationCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserInvitationCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserInvitationCodeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserInvitationCodeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserInvitationCodeCreateBulk is the builder for creating many UserInvitationCode entities in bulk.
type UserInvitationCodeCreateBulk struct {
	config
	builders []*UserInvitationCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the UserInvitationCode entities in the database.
func (uiccb *UserInvitationCodeCreateBulk) Save(ctx context.Context) ([]*UserInvitationCode, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uiccb.builders))
	nodes := make([]*UserInvitationCode, len(uiccb.builders))
	mutators := make([]Mutator, len(uiccb.builders))
	for i := range uiccb.builders {
		func(i int, root context.Context) {
			builder := uiccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserInvitationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uiccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = uiccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uiccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uiccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uiccb *UserInvitationCodeCreateBulk) SaveX(ctx context.Context) []*UserInvitationCode {
	v, err := uiccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uiccb *UserInvitationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := uiccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uiccb *UserInvitationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := uiccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserInvitationCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (uiccb *UserInvitationCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserInvitationCodeUpsertBulk {
	uiccb.conflict = opts
	return &UserInvitationCodeUpsertBulk{
		create: uiccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserInvitationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (uiccb *UserInvitationCodeCreateBulk) OnConflictColumns(columns ...string) *UserInvitationCodeUpsertBulk {
	uiccb.conflict = append(uiccb.conflict, sql.ConflictColumns(columns...))
	return &UserInvitationCodeUpsertBulk{
		create: uiccb,
	}
}

// UserInvitationCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of UserInvitationCode nodes.
type UserInvitationCodeUpsertBulk struct {
	create *UserInvitationCodeCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserInvitationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *UserInvitationCodeUpsertBulk) UpdateNewValues() *UserInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserInvitationCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *UserInvitationCodeUpsertBulk) Ignore() *UserInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserInvitationCodeUpsertBulk) DoNothing() *UserInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserInvitationCodeCreateBulk.OnConflict
// documentation for more info.
func (u *UserInvitationCodeUpsertBulk) Update(set func(*UserInvitationCodeUpsert)) *UserInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserInvitationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *UserInvitationCodeUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserInvitationCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserInvitationCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserInvitationCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
