// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/cloud-hashing-inspire/pkg/db/ent/userinvitationcode"
	"github.com/google/uuid"
)

// UserInvitationCodeQuery is the builder for querying UserInvitationCode entities.
type UserInvitationCodeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserInvitationCode
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserInvitationCodeQuery builder.
func (uicq *UserInvitationCodeQuery) Where(ps ...predicate.UserInvitationCode) *UserInvitationCodeQuery {
	uicq.predicates = append(uicq.predicates, ps...)
	return uicq
}

// Limit adds a limit step to the query.
func (uicq *UserInvitationCodeQuery) Limit(limit int) *UserInvitationCodeQuery {
	uicq.limit = &limit
	return uicq
}

// Offset adds an offset step to the query.
func (uicq *UserInvitationCodeQuery) Offset(offset int) *UserInvitationCodeQuery {
	uicq.offset = &offset
	return uicq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uicq *UserInvitationCodeQuery) Unique(unique bool) *UserInvitationCodeQuery {
	uicq.unique = &unique
	return uicq
}

// Order adds an order step to the query.
func (uicq *UserInvitationCodeQuery) Order(o ...OrderFunc) *UserInvitationCodeQuery {
	uicq.order = append(uicq.order, o...)
	return uicq
}

// First returns the first UserInvitationCode entity from the query.
// Returns a *NotFoundError when no UserInvitationCode was found.
func (uicq *UserInvitationCodeQuery) First(ctx context.Context) (*UserInvitationCode, error) {
	nodes, err := uicq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userinvitationcode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) FirstX(ctx context.Context) *UserInvitationCode {
	node, err := uicq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserInvitationCode ID from the query.
// Returns a *NotFoundError when no UserInvitationCode ID was found.
func (uicq *UserInvitationCodeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uicq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userinvitationcode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := uicq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserInvitationCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserInvitationCode entity is found.
// Returns a *NotFoundError when no UserInvitationCode entities are found.
func (uicq *UserInvitationCodeQuery) Only(ctx context.Context) (*UserInvitationCode, error) {
	nodes, err := uicq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userinvitationcode.Label}
	default:
		return nil, &NotSingularError{userinvitationcode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) OnlyX(ctx context.Context) *UserInvitationCode {
	node, err := uicq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserInvitationCode ID in the query.
// Returns a *NotSingularError when more than one UserInvitationCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (uicq *UserInvitationCodeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uicq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = &NotSingularError{userinvitationcode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := uicq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserInvitationCodes.
func (uicq *UserInvitationCodeQuery) All(ctx context.Context) ([]*UserInvitationCode, error) {
	if err := uicq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uicq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) AllX(ctx context.Context) []*UserInvitationCode {
	nodes, err := uicq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserInvitationCode IDs.
func (uicq *UserInvitationCodeQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := uicq.Select(userinvitationcode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := uicq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uicq *UserInvitationCodeQuery) Count(ctx context.Context) (int, error) {
	if err := uicq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uicq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) CountX(ctx context.Context) int {
	count, err := uicq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uicq *UserInvitationCodeQuery) Exist(ctx context.Context) (bool, error) {
	if err := uicq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uicq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uicq *UserInvitationCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := uicq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserInvitationCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uicq *UserInvitationCodeQuery) Clone() *UserInvitationCodeQuery {
	if uicq == nil {
		return nil
	}
	return &UserInvitationCodeQuery{
		config:     uicq.config,
		limit:      uicq.limit,
		offset:     uicq.offset,
		order:      append([]OrderFunc{}, uicq.order...),
		predicates: append([]predicate.UserInvitationCode{}, uicq.predicates...),
		// clone intermediate query.
		sql:    uicq.sql.Clone(),
		path:   uicq.path,
		unique: uicq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserInvitationCode.Query().
//		GroupBy(userinvitationcode.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uicq *UserInvitationCodeQuery) GroupBy(field string, fields ...string) *UserInvitationCodeGroupBy {
	group := &UserInvitationCodeGroupBy{config: uicq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uicq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uicq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.UserInvitationCode.Query().
//		Select(userinvitationcode.FieldUserID).
//		Scan(ctx, &v)
//
func (uicq *UserInvitationCodeQuery) Select(fields ...string) *UserInvitationCodeSelect {
	uicq.fields = append(uicq.fields, fields...)
	return &UserInvitationCodeSelect{UserInvitationCodeQuery: uicq}
}

func (uicq *UserInvitationCodeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uicq.fields {
		if !userinvitationcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uicq.path != nil {
		prev, err := uicq.path(ctx)
		if err != nil {
			return err
		}
		uicq.sql = prev
	}
	return nil
}

func (uicq *UserInvitationCodeQuery) sqlAll(ctx context.Context) ([]*UserInvitationCode, error) {
	var (
		nodes = []*UserInvitationCode{}
		_spec = uicq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserInvitationCode{config: uicq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uicq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uicq *UserInvitationCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uicq.querySpec()
	_spec.Node.Columns = uicq.fields
	if len(uicq.fields) > 0 {
		_spec.Unique = uicq.unique != nil && *uicq.unique
	}
	return sqlgraph.CountNodes(ctx, uicq.driver, _spec)
}

func (uicq *UserInvitationCodeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uicq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uicq *UserInvitationCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userinvitationcode.Table,
			Columns: userinvitationcode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userinvitationcode.FieldID,
			},
		},
		From:   uicq.sql,
		Unique: true,
	}
	if unique := uicq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uicq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userinvitationcode.FieldID)
		for i := range fields {
			if fields[i] != userinvitationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uicq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uicq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uicq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uicq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uicq *UserInvitationCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uicq.driver.Dialect())
	t1 := builder.Table(userinvitationcode.Table)
	columns := uicq.fields
	if len(columns) == 0 {
		columns = userinvitationcode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uicq.sql != nil {
		selector = uicq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uicq.unique != nil && *uicq.unique {
		selector.Distinct()
	}
	for _, p := range uicq.predicates {
		p(selector)
	}
	for _, p := range uicq.order {
		p(selector)
	}
	if offset := uicq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uicq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserInvitationCodeGroupBy is the group-by builder for UserInvitationCode entities.
type UserInvitationCodeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uicgb *UserInvitationCodeGroupBy) Aggregate(fns ...AggregateFunc) *UserInvitationCodeGroupBy {
	uicgb.fns = append(uicgb.fns, fns...)
	return uicgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uicgb *UserInvitationCodeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uicgb.path(ctx)
	if err != nil {
		return err
	}
	uicgb.sql = query
	return uicgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uicgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uicgb.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uicgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) StringsX(ctx context.Context) []string {
	v, err := uicgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uicgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) StringX(ctx context.Context) string {
	v, err := uicgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uicgb.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uicgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) IntsX(ctx context.Context) []int {
	v, err := uicgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uicgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) IntX(ctx context.Context) int {
	v, err := uicgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uicgb.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uicgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uicgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uicgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uicgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uicgb.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uicgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uicgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uicgb *UserInvitationCodeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uicgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uicgb *UserInvitationCodeGroupBy) BoolX(ctx context.Context) bool {
	v, err := uicgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uicgb *UserInvitationCodeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uicgb.fields {
		if !userinvitationcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uicgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uicgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uicgb *UserInvitationCodeGroupBy) sqlQuery() *sql.Selector {
	selector := uicgb.sql.Select()
	aggregation := make([]string, 0, len(uicgb.fns))
	for _, fn := range uicgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uicgb.fields)+len(uicgb.fns))
		for _, f := range uicgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uicgb.fields...)...)
}

// UserInvitationCodeSelect is the builder for selecting fields of UserInvitationCode entities.
type UserInvitationCodeSelect struct {
	*UserInvitationCodeQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uics *UserInvitationCodeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uics.prepareQuery(ctx); err != nil {
		return err
	}
	uics.sql = uics.UserInvitationCodeQuery.sqlQuery(ctx)
	return uics.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uics.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uics.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uics.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) StringsX(ctx context.Context) []string {
	v, err := uics.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uics.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) StringX(ctx context.Context) string {
	v, err := uics.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uics.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uics.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) IntsX(ctx context.Context) []int {
	v, err := uics.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uics.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) IntX(ctx context.Context) int {
	v, err := uics.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uics.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uics.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uics.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uics.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) Float64X(ctx context.Context) float64 {
	v, err := uics.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uics.fields) > 1 {
		return nil, errors.New("ent: UserInvitationCodeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uics.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) BoolsX(ctx context.Context) []bool {
	v, err := uics.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uics *UserInvitationCodeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uics.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userinvitationcode.Label}
	default:
		err = fmt.Errorf("ent: UserInvitationCodeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uics *UserInvitationCodeSelect) BoolX(ctx context.Context) bool {
	v, err := uics.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uics *UserInvitationCodeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uics.sql.Query()
	if err := uics.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
