// Code generated by entc, DO NOT EDIT.

package couponpool

const (
	// Label holds the string label denoting the couponpool type in the database.
	Label = "coupon_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the couponpool in the database.
	Table = "coupon_pools"
)

// Columns holds all SQL columns for couponpool fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
